FROM python:3.7
WORKDIR /api
COPY . /api
RUN pip install flask gunicorn
RUN pip install -r requirements.txt
RUN chmod +x ./migrate_script.sh
RUN sh ./migrate_script.sh
EXPOSE 8000
CMD ["gunicorn", "-b", "0.0.0.0:8000", "run:application"]